# Generated by Django 3.2.15 on 2023-12-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('members', models.ManyToManyField(blank=True, related_name='member', to='user.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(help_text='enter your message', max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('room', models.ManyToManyField(related_name='room', to='main.Chatroom')),
                ('senter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.userprofile')),
            ],
        ),
    ]
